######################################################################
# Automatically generated by qmake (2.01a) Wed Jan 14 15:52:07 2015
######################################################################

CONFIG += qtestlib debug precompile_header
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
INCLUDEPATH += ..

OBJECTS_DIR = build
MOC_DIR = build
RCC_DIR = build
UI_DIR = build
PRECOMPILED_DIR = build

PRECOMPILED_HEADER += stable.h

QMAKE_CXXFLAGS += -std=c++11
QMAKE_CXXFLAGS += -Wno-deprecated-register

# Input
SOURCES += ../../utility.cpp
HEADERS += ../../utility.h

SOURCES += main.cpp

SOURCES += conditiontest.cpp \
           ../condition.cpp
HEADERS += conditiontest.h \
           ../condition.h

SOURCES += documentruletest.cpp \
           ../documentrule.cpp
HEADERS += documentruletest.h \
           ../documentrule.h

SOURCES += stylesheettest.cpp \
           ../stylesheet.cpp
HEADERS += stylesheettest.h \
           ../stylesheet.h

LIBS += -lboost_filesystem \
        -lboost_iostreams \
        -lboost_regex \
	-lboost_system

