#include <boost/filesystem.hpp>
#include <boost/range/iterator_range.hpp>
#include <cassert>
#include <chrono>
#include <fstream>
#include <gtest/gtest.h>
#include <iostream>
#include <ostream>
#include <QtCore/QObject>
#include <QtCore/QProcess>
#include <QtCore/QSettings>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QTimer>
#include <QtCore/QUrl>
#include <QtCore/QVariant>
#include <QtNetwork/QNetworkAccessManager>
#include <QtNetwork/QNetworkRequest>
#include <QtTest/QSignalSpy>
#include <QtTest/QTest>
#include <QtWebKit/QWebElement>
#include <QtWebKitWidgets/QWebFrame>
#include <QtWebKitWidgets/QWebPage>
#include <QtWidgets/QApplication>
#include <thread>
#include <utime.h>
