#include <QtCore/QObject>
#include <QtGui/QApplication>
#include <QtTest/QSignalSpy>
#include <QtTest/QtTest>
#include <boost/algorithm/string/trim.hpp>
#include <boost/filesystem.hpp>
#include <boost/filesystem/fstream.hpp>
#include <boost/range/iterator_range.hpp>
#include <fstream>
#include <string>
#include <util/url.h>
