######################################################################
# Automatically generated by qmake (2.01a) Wed Jan 14 15:52:07 2015
######################################################################

CONFIG += qtestlib debug precompile_header
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
INCLUDEPATH += ..

OBJECTS_DIR = build
MOC_DIR = build
RCC_DIR = build
UI_DIR = build
PRECOMPILED_DIR = build

PRECOMPILED_HEADER += stable.h

QMAKE_CXXFLAGS += -std=c++11
QMAKE_CXXFLAGS += -Wno-deprecated-register
QMAKE_CXXFLAGS += -g

# Input
SOURCES += main.cpp

SOURCES += utilitytest.cpp \
           ../utility.cpp
HEADERS += utilitytest.h \
           ../utility.h

SOURCES += styletest.cpp \
           ../styles.cpp \
	   ../css/stylesheet.cpp \
	   ../css/documentrule.cpp \
	   ../css/condition.cpp
HEADERS += styletest.h \
           ../styles.h \
	   ../css/stylesheet.h \
	   ../css/documentrule.h \
	   ../css/condition.h

LIBS += -lboost_filesystem \
        -lboost_iostreams \
	-lboost_regex \
	-lboost_system

