#include <boost/filesystem.hpp>
#include <boost/filesystem/path.hpp>
#include <boost/functional/hash.hpp>
#include <boost/serialization/nvp.hpp>
#include <boost/utility/string_ref.hpp>
#include <cassert>
#include <ostream>
#include <QMetaType>
#include <QtCore/QDebug>
#include <QtCore/QHash>
#include <QtCore/QLoggingCategory>
#include <QtCore/QMetaType>
#include <QtCore/QObject>
#include <QtCore/QSettings>
#include <QtCore/QString>
#include <QtCore/QtGlobal>
#include <QtCore/QUrl>
#include <QtCore/QVariant>
#include <QtGui/QColor>
#include <string>
#include <type_traits>
#include <utility>
#include <vector>
