#include <adblock/api.h>
#include <algorithm>
#include <boost/algorithm/string.hpp>
#include <boost/filesystem/fstream.hpp>
#include <boost/filesystem.hpp>
#include <boost/filesystem/path.hpp>
#include <boost/iostreams/device/mapped_file.hpp>
#include <boost/make_unique.hpp>
#include <boost/optional.hpp>
#include <boost/range/algorithm.hpp>
#include <boost/range/iterator_range.hpp>
#include <boost/regex.hpp>
#include <cassert>
#include <climits>
#include <cstdio>
#include <followredirectreply.h>
#include <fstream>
#include <ios>
#include <iterator>
#include <memory>
#include <QtCore/QByteArray>
#include <QtCore/QCryptographicHash>
#include <QtCore/QDateTime>
#include <QtCore/QDebug>
#include <QtCore/QDebug> //TODO
#include <QtCore/QFile>
#include <QtCore/QFileSystemWatcher>
#include <QtCore/QIODevice>
#include <QtCore/QObject>
#include <QtCore/QSettings>
#include <QtCore/QString>
#include <QtCore/QTimer>
#include <QtCore/QUrl>
#include <QtNetwork/QNetworkAccessManager>
#include <QtNetwork/QNetworkReply>
#include <QtNetwork/QNetworkRequest>
#include <QtWebKit/QWebElement>
#include <QtWebKitWidgets/QWebFrame>
#include <QtWebKitWidgets/QWebView> //TODO
#include <QtWidgets/QApplication>
#include <queue>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>
#include <webpage.h>
